// UI Timeline Runtime

import TimelinePlayer, { TimelineData, TimelineLoopMode } from "./TimelinePlayer";

const { ccclass, property } = cc._decorator;

@ccclass
export default class TimelineComponent extends cc.Component {
	@property({ type: cc.JsonAsset, tooltip: "Timeline JSON generated by UI Timeline Editor" })
	public timelineAsset: cc.JsonAsset = null;

	@property
	public autoPlay = false;

	@property({ type: cc.Enum({ none: 0, loop: 1, pingpong: 2 }) })
	public loopMode = 0;

	@property
	public speed = 1;

	private player: TimelinePlayer | null = null;
	private paused = false;

	public onLoad(): void {
		this.player = new TimelinePlayer(this.node, { owner: this });
		this.reload();
	}

	public start(): void {
		if (this.autoPlay) {
			this.play();
		}
	}

	public update(dt: number): void {
		if (!this.player || this.paused) return;
		this.player.update(dt, this.speed);
	}

	public reload(): void {
		if (!this.player) return;
		this.player.load(this.getTimelineData());
	}

	public play(): void {
		if (!this.player) return;
		this.paused = false;
		this.player.play(this.getTimelineData(), { owner: this });
	}

	public pause(): void {
		this.paused = true;
		if (this.player) this.player.pause();
	}

	public resume(): void {
		this.paused = false;
		if (this.player) this.player.resume();
	}

	public stop(): void {
		this.paused = false;
		if (this.player) this.player.stop(true);
	}

	public sample(time: number): void {
		if (!this.player) return;
		if (!this.player.hasTimeline()) {
			this.reload();
		}
		this.player.sample(time, false);
	}

	public getCurrentTime(): number {
		return this.player ? this.player.currentTime : 0;
	}

	public isPlaying(): boolean {
		return !!(this.player && this.player.playing);
	}

	private getTimelineData(): TimelineData | null {
		if (!this.timelineAsset || !this.timelineAsset.json) return null;
		const data = this.cloneData(this.timelineAsset.json) as TimelineData;
		data.loopMode = this.getLoopMode(data.loopMode);
		return data;
	}

	private getLoopMode(assetLoopMode?: TimelineLoopMode): TimelineLoopMode {
		if (this.loopMode === 1) return "loop";
		if (this.loopMode === 2) return "pingpong";
		return assetLoopMode || "none";
	}

	private cloneData<T>(value: T): T {
		return JSON.parse(JSON.stringify(value));
	}
}
